/**
 * This code was generated by Builder.io.
 */
import React from "react";
import DateFormatter from "./DateFormatter.jsx";
import ReadMoreButton from "./ReadMoreButton.jsx";
import ProgressBar from "./ProgressBar.jsx";

function ContentSection({ date, title, description }) {
  return (
    <div className="flex flex-col ml-5 w-[65%] max-md:ml-0 max-md:w-full">
      <div className="flex gap-10 self-stretch my-auto max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col grow shrink-0 items-start text-base font-medium basis-0 w-fit">
          <DateFormatter date={date} />
          <h2 className="mt-6 text-2xl font-bold text-slate-900">{title}</h2>
          <p className="self-stretch mt-6 leading-6 text-gray-600">
            {description}
          </p>
          <ReadMoreButton />
        </div>
        <ProgressBar />
      </div>
    </div>
  );
}

export default ContentSection;
