/**
 * This code was generated by Builder.io.
 */
import React from "react";

function DateFormatter({ date }) {
  return <time className="text-slate-500">{date}</time>;
}

export default DateFormatter;
