/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ImageComponent() {
  return (
    <div className="flex overflow-hidden flex-col grow rounded-3xl shadow-lg max-md:mt-10">
      <div className="flex shrink-0 rounded-3xl h-[300px]" />
    </div>
  );
}

export default ImageComponent;
