/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ProgressBar() {
  return (
    <div className="flex flex-col my-auto">
      <div
        className="flex shrink-0 bg-red-500 rounded-xl h-[30px] shadow-[0px_0px_20px_rgba(252,56,56,0.3)]"
        role="progressbar"
        aria-valuenow="30"
        aria-valuemin="0"
        aria-valuemax="100"
      />
      <div
        className="flex shrink-0 mt-2 rounded-xl bg-sky-950 h-[11px] w-[11px]"
        role="progressbar"
        aria-valuenow="11"
        aria-valuemin="0"
        aria-valuemax="100"
      />
      <div
        className="flex shrink-0 mt-2 rounded-xl bg-sky-950 h-[11px] w-[11px]"
        role="progressbar"
        aria-valuenow="11"
        aria-valuemin="0"
        aria-valuemax="100"
      />
    </div>
  );
}

export default ProgressBar;
