/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ReadMoreButton() {
  return (
    <button className="px-9 py-5 mt-9 tracking-wider text-center text-white rounded-[50px] shadow-[0px_14px_80px_rgba(252,56,56,0.4)] max-md:px-5">
      {" "}
      READ MORE{" "}
    </button>
  );
}

export default ReadMoreButton;
