/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageComponent from "./ImageComponent.jsx";
import ContentSection from "./ContentSection.jsx";

function RefactoredComponent() {
  return (
    <section className="flex flex-col justify-center items-center px-16 py-96 max-md:px-5 max-md:py-24">
      <article className="py-12 pr-5 max-w-full bg-white rounded-3xl shadow-[0px_14px_80px_rgba(34,35,58,0.2)] w-[800px]">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[35%] max-md:ml-0 max-md:w-full">
            <ImageComponent />
          </div>
          <ContentSection
            date="26 December 2019"
            title="Lorem Ipsum Dolor"
            description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Recusandae voluptate repellendus magni illo ea animi?"
          />
        </div>
      </article>
    </section>
  );
}

export default RefactoredComponent;
